### ISSUE TITLE
CIS Windows 10 list bugs

### ISSUE THREAD

**Issue by thebalagee** [scipag/HardeningKitty#1]
Hello,
just a few remarks regarding the _finding_list_cis_microsoft_windows_10_enterprise_machine.csv_:
- 18.8.3.1 - the recommended value should be '0' (disabled)
- 18.8.4.1 and 18.8.4.2 are swapped, and default credential check is no longer part of this version of CIS benchmark. It should be 'Remote host allows delegation of non-exportable credentials'
- '18.5.14.1.1' does not exist in CIS, it should be '18.5.14.1'

**Comment by 0x6d69636b** [comment]
Thank you for the remarks, all items were fixed in the commit (https://github.com/scipag/HardeningKitty/commit/ac405f3fef47af5a0f308f4862b880bfad105538). The ID 18.5.14.1 is split in x.1 for _NETLOGON_ and x.2 for _SYSVOL_.
