### ISSUE TITLE
Hardening Jump Server 

### ISSUE THREAD

**Issue by adelhendou97** [scipag/HardeningKitty#10]

**Comment by adelhendou97** [comment]
Hello, i wanted to create a RDP Jump Server and hardening  it with hardeningKitty but i dont which lines i should alter without affecting the security level. Env : Windows 10 pro  x64

**Comment by 0x6d69636b** [comment]
Can you please elaborate on what security level you mean?

**Comment by 0x6d69636b** [comment]
Closed after inactivity
