### ISSUE TITLE
Windows Feature install of defender application guard requests for reboot

### ISSUE THREAD

**Issue by Geo-Ron** [scipag/HardeningKitty#12]
This reboot request halts requires human input.
This halts an automated process.

**Comment by 0x6d69636b** [comment]
I suppressed a reboot in this commit: https://github.com/0x6d69636b/windows_hardening/commit/2bc8e1595259e8df33d855ccf421f3744cbd74d9 

Note this is the stable repo, the commit will not be pushed here until the next release. You can try it out on this repo: https://github.com/0x6d69636b/windows_hardening

**Comment by Geo-Ron** [comment]
Great work! Thanks!
You are the best!
