### ISSUE TITLE
Network Provider: Hardened UNC Paths (SYSVOL)

### ISSUE THREAD

**Issue by FLeven** [scipag/HardeningKitty#13]
[*] 16.05.2022 15:05:49 - Getting machine information
[*] Domain role: MemberServer
[*] Windows: Windows Server 2022 Datacenter
[*] Windows edition: ServerDatacenter
[*] Windows version: 2009
[*] Windows build: 20348.1.amd64fre.fe_release.210507-1500
[*] System-locale: de-DE
[*] Powershell Version: 5.1

Commandline:
`Invoke-HardeningKitty -EmojiSupport -FileFindingList .\lists\finding_list_msft_security_baseline_windows_server_2022_21h2_member_machine.csv`

`ID 10653, Network Provider: Hardened UNC Paths (NETLOGON), Result=RequireMutualAuthentication=1,RequireIntegrity=1, Severity=Passed`

`[😿] ID 10654, Network Provider: Hardened UNC Paths (SYSVOL), Result=RequireMutualAuthentication=1,RequireIntegrity=1, Recommended=RequireMutualAuthentication=1, RequireIntegrity=1, Severity=Medium`

The recommendation of the second case. contains a space character and might lead to the **Severity=Medium** instead of **Severity=Passed**. Both cases are configured exactly the same on my systems.

**Comment by 0x6d69636b** [comment]
Hi Felix
Thank you for rising this issue. I created a workaround for Hardened UNC path in the development version of HardeningKitty, see https://github.com/0x6d69636b/windows_hardening/commit/05f2a2d9728de6ea4437020baf3bed4ddff6a3d5. In the next release this exception will published on this repo as well.

**Comment by 0x6d69636b** [comment]
And now I released a new version and this issue is fixed in this repo as well
