### ISSUE TITLE
"Window Manager\Window Manager Group" SID not shown in Result

### ISSUE THREAD

**Issue by catchingknives** [scipag/HardeningKitty#24]
I did a scan of a server against the BSI ND Machine baseline and in the scan result (CSV) for ID 279 (Increase scheduling priority), it shows only `BUILTIN\Administrators` as a result, despite the `Window Manager\Window Manager Group` also being configured via its SID (S-1-5-90-0) which I got from [here](https://social.technet.microsoft.com/Forums/windowsserver/en-US/cdbf40a2-24db-49eb-8e3b-455cfb7a8434/looking-for-quotwindow-managerwindow-manager-groupquot-sid?forum=winserver8gen). I would expect that SID to show up in the "Result" column as well, which isn't the case. For other settings I use S-1-0-0 for `Nobody` and those settings get a pass too, so I'm not sure it is related to the fact I am using a SID here per se.

Caveats: I'm not entirely convinced doing it via the SID is correct and the Windows Server language is German.

**Comment by 0x6d69636b** [comment]
What do you mean by doing/setting it via SID? What is the output of the command `secedit /export /cfg $TempFileName /areas USER_RIGHTS` (you have to set a real path for $TempFileName)?
