### ISSUE TITLE
Wrong default value for AlwaysInstallElevated

### ISSUE THREAD

**Issue by v-p-b** [scipag/HardeningKitty#26]
According to the [documentation](https://learn.microsoft.com/en-us/windows/win32/msi/alwaysinstallelevated):

"To install a package with elevated (system) privileges, set the AlwaysInstallElevated value to "1" under both of the following registry keys:"

This implies that when these keys are missing, the setting is not the same as if the setting value was 1. 

This list  (and others) however assume the value to be 1 by default:

https://github.com/scipag/HardeningKitty/blame/7751c3c303ba77f30d9d59362914018800eeb0bb/lists/finding_list_cis_microsoft_windows_10_enterprise_20h2_user.csv#L14

This results in false positive findings.

**Comment by 0x6d69636b** [comment]
Thank you, this issue is fixed in the [development repo](https://github.com/0x6d69636b/windows_hardening/commit/704f360897ae1b1c97397eeb98cbcbd65b773f4a) and will be fixed here in the next update.
