### ISSUE TITLE
Automatic creation of finding lists

### ISSUE THREAD

**Issue by derry43** [scipag/HardeningKitty#31]
HardeningKitty is a great tool and has been very helpful for creating gold images etc.

Do you have a scripted method for creating the finding lists from the STIG xml or pol files? It looks as though it might be possible, but not sure if all the required information is there.

Perhaps you could provide a short description of how you go about generating the finding lists from a STIG, this would  be helpful for those looking to add new lists of keep theirs up to date.

thanks in advance.

**Comment by 0x6d69636b** [comment]
I use a sqlite database to manage all findings and lists and to generate csv lists. I don't have any automation process to create a new list. The sources are all different as CIS has PDFs, MSFT has an Excel file, BSI has another Excel and so on. If I have already a similar list like CIS Benchmark for Windows 10, then I can copy this list and I'm looking for changes by hand.

For automation I need how to configure the recommendation, the easiest way would be a registry key. If this bit is missing and the automation process must look for a matching finding name/text, which would be doable as well. However, it would be necessary to create for each source it's own script. So if somebody likes to help creating script, please ping me
