### ISSUE TITLE
The finding list was not found

### ISSUE THREAD

**Issue by sssseossss** [scipag/HardeningKitty#33]
Hi!
just installed HK and cannot run it due to the following error in the output. Can you help please?

PS C:\Users\XXXXXXX\Desktop> Invoke-HardeningKitty -EmojiSupport

      =^._.^=
     _(      )/  HardeningKitty 0.9.0-1670934249

[*] 2023-04-07 20:20:35 - Starting HardeningKitty

[*] 2023-04-07 20:20:35 - Getting machine information
[*] Hostname: XXXX
[*] Domain: XXXX
[*] Domain role: Member Server
[*] Install date: 01/11/2016 07:16:02
[*] Last Boot Time: 04/06/2023 08:17:12
[*] Uptime: 1.12:03:23.2387107
[*] Windows: Microsoft Windows Server 2012 R2 Standard
[*] Windows version: 6.3.9600
[*] Windows build: 9600
[*] System-locale: lt-LT
[*] Powershell Version: 4.0

[*] 2023-04-07 20:20:36 - Language warning
[?] 2023-04-07 20:20:36 - HardeningKitty was developed for the system language 'en-US'. This system uses 'lt-LT' Languag
e-dependent analyses can sometimes produce false results. Please create an issue if this occurs.

[*] 2023-04-07 20:20:36 - Getting user information
[*] Username: XXXXXX\XXXXXX
[*] Is Admin: True
[!] 2023-04-07 20:20:36 - The finding list C:\Users\XXXXXXX\Desktop\lists\finding_list_0x6d69636b_machine.csv was not fo
und.

**Comment by 0x6d69636b** [comment]
Please make sure that the folder _lists_ exists on the location, or use the parameter _-FileFindingList_ to point to the finding list as documented under [examples](https://github.com/scipag/HardeningKitty#examples).
