### ISSUE TITLE
CIS 22H2 list availability

### ISSUE THREAD

**Issue by Cyb3rC3lt** [scipag/HardeningKitty#34]
Hi there,

Just working on a Windows 11 22H2 machine today. Any chance you have this CIS list for 22H2? Unless you think 21H2 would suffice....

finding_list_cis_microsoft_windows_11_enterprise_**21**h2_machine.csv

Thanks

**Comment by 0x6d69636b** [comment]
Hi @Cyb3rC3lt 

To build/update a CIS list is a piece of work (comparing the PDF with my lists) but I did it now for all current Windows releases and the new versions of CIS. The lists are now in the development repo, here: https://github.com/0x6d69636b/windows_hardening/commit/09858da476d339dc0957f7c79ebffd42161edea1

**Comment by Cyb3rC3lt** [comment]
Thanks very much Michael, that is very useful. Much appreciated.
