### ISSUE TITLE
Which rules from finding_list_0x6d69636b_machine.csv affect RDP?

### ISSUE THREAD

**Issue by b3d3c** [scipag/HardeningKitty#35]
Hello,

I am trying to harden a device but allow RDP connections. Although, after executing it and deleting the fDenyTSConnections key, I am having issues to connect using both an Admin user and a local user.

Thank you.

**Comment by 0x6d69636b** [comment]
The user rights assignment rules ID 1200, 1203, and 1206, all Remote Desktop rules, such as ID 1734, 1735, 1736, 1737, 1738, and 1739, and the firewall rule ID 2301. My guess is that the user assignment rules need to be configured less restrictively for your purpose.
