### ISSUE TITLE
Mishandling of "Never minutes" in Account Lockout Duration checks

### ISSUE THREAD

**Issue by v-p-b** [scipag/HardeningKitty#36]
According to my tests when Account Lockout Duration is set to 0, Windows reports the value as "Never", which is also reflected in HardeningKitty's output. 

According to [documentation](https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/account-lockout-duration):

> A value of 0 specifies that the account will be locked out until an administrator explicitly unlocks it.

HardeningKitty [specifies](https://github.com/scipag/HardeningKitty/blob/10367df0204780d0e1a41a4b40506b5db025c04c/lists/finding_list_cis_microsoft_windows_10_enterprise_1809_machine.csv?plain=1#L8) a numeric threshold for this value, while
a) the "Never" string can't be handled with such a rule
b) 0 as a special case can't be handled by a "bigger is better" kind of rule

I think the "0" setting is more secure than any expiring value, so it should be accepted, but I don't know how much flexibility the rule format of HardeningKitty provides to handle the above edge case.

**Comment by 0x6d69636b** [comment]
You refer to a CIS benchmark list, there the CIS specifications are implemented accordingly in HardeningKitty finding lists and I have no influence on which values are set

**Comment by 0x6d69636b** [comment]
![image](https://github.com/scipag/HardeningKitty/assets/13913706/df52babc-df49-4611-8e55-c84753e18dd4)
![image](https://github.com/scipag/HardeningKitty/assets/13913706/28565c08-a186-4491-9202-0c8aeeafd2e7)

**Comment by v-p-b** [comment]
I think - considering the meaning of possible values - CIS is vague here, as "lockout never expires" can be interpreted as "lockout expires later than 15 minutes".  

Note that this requirement is also reflected in MS Security Baseline lists, but I can't test the official compliance tool right now. 

Since this case is unclear even at the level of the compliance requirement definitions, I think it'd be fair to close this issue, but I also see the benefit in having this documented at least as part of this issue.

**Comment by v-p-b** [comment]
Thanks for the feedback, I definitely don't want to start aguing about CIS here.  Closing this one.
