### ISSUE TITLE
Requires Admin Privilege

### ISSUE THREAD

**Issue by piyatila** [scipag/HardeningKitty#38]
Hello, while I run the script and I want to save it as CSV file, however I encounter this kind of error to some of our configured policy.

How to bypass ?
![image](https://github.com/scipag/HardeningKitty/assets/139862977/a54d6545-0b49-4da7-9bc2-45c32cfd81ca)

**Comment by 0x6d69636b** [comment]
HardeningKitty checks if a user is admin before using functions that require admin rights. If you want to check these settings, you need to run the script as admin. You could theoretically modify the script and set $IsAdmin = true to bypass the check, but you'll get access denied and other error messages.
