### ISSUE TITLE
unauthenticated guest access 

### ISSUE THREAD

**Issue by ayeyo0** [scipag/HardeningKitty#39]
I have been trying to figure out which rule has been giving me issues with network drives. wont let me add drives due to unauthenticated guest access.

**Comment by 0x6d69636b** [comment]
Please be more specific, otherwise I can only guess. If you have hardened a server and now want to connect a share from that server, any rule from the category _User Rights Assignment_ that include Guest are possible culprits

**Comment by ayeyo0** [comment]
"you can't access this shared folder because your organization's security policies block unauthenticated guest access" is the error message that i get when i try to add an SMB

**Comment by 0x6d69636b** [comment]
I need the following information to help you:

1. Did it work before you used HailMary mode?
2. Which finding list(s) did you use?
3. On what system did you run HailMary (server and/or client)?
4. How do you mount the share (command)?
