### ISSUE TITLE
Backup Parameter Not Found

### ISSUE THREAD

**Issue by thetechgy** [scipag/HardeningKitty#4]
After importing the module, when executing `Invoke-HardeningKitty -Mode Config -Backup` as indicated in the Readme.md , PowerShell returns the following error regarding the Backup parameter:
```
Invoke-HardeningKitty : A parameter cannot be found that matches parameter name 'Backup'.
At line:1 char:36
+ Invoke-HardeningKitty -Mode Config -Backup
+                                    ~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-HardeningKitty], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Invoke-HardeningKitty
```

**Comment by 0x6d69636b** [comment]
Which version did you use? I can't reproduce the issue in the current version:

![hardeningkitty_backup](https://user-images.githubusercontent.com/13913706/128622496-7da2bedd-31a4-480b-892e-5a7d60530201.png)

**Comment by thetechgy** [comment]
The current release from this repo - 0.6.0. This is a new Windows 10 install of 20H1. I also tried the same syntax you used and got the same error:
```
PS C:\Users\TechGy\Downloads\HardeningKitty-v.0.6.0\HardeningKitty-v.0.6.0> Invoke-HardeningKitty -FileFindingList .\lists\finding_list_0x6d69636b_machine.csv -Backup -Log -Report
Invoke-HardeningKitty : A parameter cannot be found that matches parameter name 'Backup'.
At line:1 char:84
+ ... ndingList .\lists\finding_list_0x6d69636b_machine.csv -Backup -Log -R ...
+                                                           ~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-HardeningKitty], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Invoke-HardeningKitty
```

**Comment by 0x6d69636b** [comment]
All right, you can use the current version in the repository. Releases are only made at sporadic intervals and the 0.6.0 release does not include the backup method.

**Comment by thetechgy** [comment]
I was just noticing that after comparing 0.6.0 to master. I'll use the latest version, thanks!

> All right, you can use the current version in the repository. Releases are only made at sporadic intervals and the 0.6.0 release does not include the backup method.
