### ISSUE TITLE
question

### ISSUE THREAD

**Issue by hangookfreak** [scipag/HardeningKitty#42]
I have this setup on a multitude of computers but we are running issues with certain smb network drives connecting.

**Comment by hangookfreak** [comment]
it does work without it as we have some computers that run it where we havent put HK on yet. 
22h2
client side
i have tried manually mounting as well as a batch file

**Comment by 0x6d69636b** [comment]
As CIS, Microsoft Security Baseline and 0x6d69636b Windows 10 are lists for 22H2, please be more specific

**Comment by hangookfreak** [comment]
finding_list_msft_security_baseline_windows_10_22h2_user.csv

**Comment by hangookfreak** [comment]
sorry the machine one

**Comment by hangookfreak** [comment]
the weird thing is that one other network drives that we map is able to connect. we are able to ping the drive that doesnt connect as well but it wont connect. nothing within event viewer.

**Comment by 0x6d69636b** [comment]
Okay, let's see. You only did the hardening on the client, not on the server. How is the authentication done, local user or domain users, over Kerberos or NTLM? Is the server also Windows or an older system? Do you relay on stored passwords?

**Comment by hangookfreak** [comment]
nothing is done server side. authentication is done by using a local account on the server. no domain.server is also windows. most likely an older system.

**Comment by 0x6d69636b** [comment]
It may be NTLM related, try _Microsoft network client: Digitally sign communications (always)_, _Network security: LAN Manager authentication level_, and/or _Network security: Minimum session security for NTLM SSP based (including secure RPC)_

**Comment by hangookfreak** [comment]
let me check those.

**Comment by hangookfreak** [comment]
none of those worked
additionally SMB 1 was turned on as well

**Comment by 0x6d69636b** [comment]
Did you check _Configure SMB v1 client driver_ as well?

**Comment by hangookfreak** [comment]
yup. ive checked all SMB settings All Lanman settings all RPC settings

**Comment by hangookfreak** [comment]
any other ideas on what it can be?
does this HK script also change anything in group policy or security policies?

**Comment by 0x6d69636b** [comment]
No, HardeningKitty does not/cannot change group policies. If a policy is applied, any changes made by HardeningKitty will be overwritten. The account settings are for the local system and should not change the behaviour of the remote system. Sorry, I ran out of ideas what could be causing this problem
