### ISSUE TITLE
question about scripts

### ISSUE THREAD

**Issue by hangookfreak** [scipag/HardeningKitty#43]
hello. 

I was wondering if there are any sections specifically that wouldn't allow for batch files to run. it is a net use batch file that we are trying to implement but so far I have not found any script related lines that would stop them from running. I am able to manually add them through file explorer. thnak you

**Comment by 0x6d69636b** [comment]
No, there are no specific hardening settings against the execution of batch scripts

**Comment by hangookfreak** [comment]
anything within the HK that could be related to batchfiles or running scripts like that

**Comment by 0x6d69636b** [comment]
No, HardeningKitty has no measures against running batch scripts. Perhaps you're using AppLocker or other application control solutions?
