### ISSUE TITLE
Incorrect Control ID in win10 Enterprise 22h2 189.7.1.5.1

### ISSUE THREAD

**Issue by Josh-Tucker** [scipag/HardeningKitty#44]
Hi, in  `lists/finding_list_cis_microsoft_windows_10_enterprise_22h2_machine.csv`  control ID 18.9.7.1.5.1 on line 347 is incorrectly labelled as 189.7.1.5.1.

**Comment by 0x6d69636b** [comment]
Thanks for reporting this issue. I have fixed it in the dev repo and will sync it with this repo later
