### ISSUE TITLE
Check how to execute the function Create a Group Policy (experimental) added from v0.91

### ISSUE THREAD

**Issue by hitoshi-yamaguchi** [scipag/HardeningKitty#50]
The function Create a Group Policy (experimental) has been added since v0.91. Could you please confirm how to execute it?

Invoke-HardeningKitty -Mode GPO -FileFindingList .\lists\finding_list_0x6d69636b_machine.csv -GPOName HardeningKitty-Machine-01

If you specify an appropriate name in the -GPOName part of the above command, the following error will occur.
Get-GPRegistryValue: I get a message that there is no GPO named xxx in my domain.

Also, if you specify an existing GPO, a message will appear stating that you do not have access rights.

Is it actually a command that creates a domain policy?
How should I specify how to apply it to local policy?

**Comment by hitoshi-yamaguchi** [comment]
bummer,
I wanted to change the local group policy all at once, but I'm thinking of another method.

**Comment by 0x6d69636b** [comment]
You can change the settings locally on a system in Hail Mary mode, but your configuration will not be visible in the local Group Policy Editor

**Comment by hitoshi-yamaguchi** [comment]
exactry. If you change the local group policy in this state, the one you updated with HailMary will be reverted. I heared that Microsoft doesn't recommend changing the registry directly.
