### ISSUE TITLE
Windows defender blocked

### ISSUE THREAD

**Issue by voctotgexp** [scipag/HardeningKitty#52]
I got this error:

_Get-MpComputerStatus : A general error occurred that is not covered by a more specific error code.
At C:\Program Files\WindowsPowerShell\Modules\HardeningKitty\0.9.2\HardeningKitty.psm1:1196 char:37
+                     $ResultOutput = Get-MpComputerStatus
+                                     ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_MpComputerStatus:ROOT\Microsoft\...pComputerStatus) [Get-MpComputerS 
   tatus], CimException
    + FullyQualifiedErrorId : HRESULT 0x800106ba,Get-MpComputerStatus
 
The Hardening Score is: 3.18
Unable to find the specified field.__

Seemed Windows Defender blocked or disabled. Is there any way to get around? Thank you

**Comment by 0x6d69636b** [comment]
Please post the output of the Get-MpComputerStatus command in PowerShell. Are you running antivirus software other than Microsoft Defender?

**Comment by voctotgexp** [comment]
Hi Mike,

Please see below:
***@***.***

I have Crowdstrike.

Thank you

--
Victor Octavianus / Field System Engineer / OTG
Mobile: (929) 618-2104 / OTGexp.com


From: Michael Schneider ***@***.***>
Sent: Monday, April 29, 2024 3:00 PM
To: scipag/HardeningKitty ***@***.***>
Cc: Victor Octavianus ***@***.***>; Author ***@***.***>
Subject: EXT*Re: [scipag/HardeningKitty] Windows defender blocked (Issue #52)

EXT* This email is from outside the company. Use caution & trust the source before clicking links or opening attachments!

Please post the output of the Get-MpComputerStatus command in PowerShell. Are you running antivirus software other than Microsoft Defender?

**Comment by 0x6d69636b** [comment]
I have tried to replicate the error by installing a different AV engine but Get-MpComputerStatus does not break on my test system. Normally, the try ... catch should prevent your error. Could you please run this command and post the result here:

```powershell
try { $Output = Get-MpComputerStatus -ErrorAction SilentlyContinue; $Result="SUCCESS" } catch { $Result="FAILED" } $Result
```
