### ISSUE TITLE
Windows server restore / Filter in HailMary mode

### ISSUE THREAD

**Issue by Blue-i-y** [scipag/HardeningKitty#56]
Hi,

First of all, I want to thank you for this repository.

I've encountered a couple of issues while using the code. The first issue is that the restore point functionality seems to be available only for computers. When I tried using it with a server, I had to create a manual restore point to utilize the HailMary mode, and I was forced to use the -SkipRestorePoint option.

The second issue is related to category filtering. When I filter by category and use the HailMary mode, the hardening is applied to all categories, not just the selected ones.

Thank you for your attention to these matters.

Best regards

**Comment by 0x6d69636b** [comment]
Hi @Blue-i-y 

Thanks for your feedback :) 

According to Microsoft, "_System restore points and the ComputerRestore cmdlets are supported only on client operating systems", so unfortunately there is nothing more I can do. Would it help if you got an additional error message on a server operating system?

For now, the filter function is only supported in Audit and Config mode. As the HailMary mode is a delicate matter, I suggest you create your own file and remove all the lines you want to filter.

All the best

**Comment by Blue-i-y** [comment]
Hi @0x6d69636b,

The error message you provided is sufficient for now.

Thanks again for your assistance.

Best regards

**Comment by Blue-i-y** [comment]
Hi @0x6d69636b,

The error message you provided is sufficient for now.

Thanks again for your assistance.

Best regards
